app/post/models.py
import datetime

from sqlalchemy import Column, Integer, DateTime, String, ForeignKey, Text
from sqlalchemy.orm import relationship

from app.database import Base


class Post(Base):
    __tablename__ = 'post'
    uid = Column(Integer, primary_key=True)
    title = Column(String)
    author_id = Column(Integer, ForeignKey('user.uid'))
    author = relationship('User', back_populates='posts')
    content = Column(Text)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    last_update = Column(DateTime, onupdate=datetime.datetime.utcnow)

    def __init__(self, title, author, content):
        self.title = title
        self.author = author
        self.content = content

    def __repr__(self):
        return f'<Post ({self.uid})>'

app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

# Create your forms here.


class PostForm(FlaskForm):
    title = StringField('title', validators=[DataRequired()])
    content = TextAreaField('content', validators=[DataRequired()])
    submit = SubmitField('Save Post')

app/post/views.py
from flask import Blueprint, render_template, abort, request, g, session, redirect, url_for

from app.auth.decorators import login_required, ownership_required
from app.database import db_session
from app.post.forms import PostForm
from app.post.models import Post

bp = Blueprint('post', __name__, url_prefix='/posts', template_folder='templates/post')


@bp.route('/')
@login_required
def list_posts():
    posts = Post.query.all()
    return render_template('list.html', posts=posts)


@bp.route('/<int:uid>')
@login_required
def retrieve_post(uid):
    post = Post.query.filter(Post.uid == uid).one_or_none()
    if post is None:
        abort(404)
    return render_template('detail.html', post=post)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        author = g.user
        content = form.content.data

        post = Post(
            title=title,
            author=author,
            content=content,
        )
        db_session.add(post)
        db_session.commit()
        return redirect(url_for('post.retrieve_post', uid=post.uid))
    return render_template('form.html', form=form)


@bp.route('/<int:uid>/update', methods=('GET', 'POST'))
@login_required
@ownership_required(Post, 'author')
def update_post(uid):
    post = Post.query.get(uid)
    if post is None:
        abort(404)

    form = PostForm(obj=post)
    if form.validate_on_submit():
        form.populate_obj(post)
        db_session.commit()
        return redirect(url_for('post.retrieve_post', uid=post.uid))
    return render_template('form.html', form=form)


@bp.route('/<int:uid>/delete', methods=('GET', 'POST'))
@login_required
@ownership_required(Post, 'author')
def delete_post(uid):
    post = Post.query.get(uid)
    if post is None:
        abort(404)
    if request.method == 'POST':
        db_session.delete(post)
        db_session.commit()
        return redirect(url_for('post.list_posts'))
    return render_template('delete.html', post=post)

app/post/templates/post/delete.html
<form method="POST">
    <p>Are you sure to delete post {{ post.title }}?</p>
    <input type="submit" value="Delete">
</form>

app/post/templates/post/detail.html
<div>
    <div>{{ post.title }}</div>
    <div>{{ post.author.name }}</div>
    <div>{{ post.content }}</div>
</div>

app/post/templates/post/form.html
<h3>Post</h3>
<form method="POST">
    <div>{{ form.csrf_token }}</div>
    <div>{{ form.title.label }} {{ form.title }}</div>
    <div>{{ form.content.label }} {{ form.content }}</div>
    <div>{{ form.submit }}</div>
    <div>{{ form.errors }}</div>
</form>

app/post/templates/post/list.html
<div>
    <a href="{{ url_for('post.create_post') }}">Create Post</a>
    {% if posts|length > 0 %}
    <ul>
        {% for post in posts %}
        <li><a href="{{ url_for('post.retrieve_post', uid=post.uid) }}">{{ post.title }} - {{ post.author.name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <div>No posts available.</div>
    {% endif %}
</div>